# This is a basic workflow to help you get started with Actions

name: Deploy VM

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_vm:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run terraform script
        shell: bash
        run: |
          cd ./KVM/Ubuntu/
          terraform init
          terraform apply -auto-approve

      - name: Increase VM disk size
        shell: bash
        run: |
          virsh shutdown ubuntu-terraform && sleep 3s && \
          echo ${{ secrets.LOCAL_PASSWORD }} | sudo qemu-img resize /var/lib/libvirt/images/ubuntu.qcow2 +10G && sleep 3s && \
          virsh start ubuntu-terraform
